using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MSU.Models
{
    public class Course
    {
        // The DatabaseGenerated attribute with the None parameter on the CourseID property specifies that primary key values are provided by the user rather than generated by the database.
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name ="Course Number")]
        public int CourseId { get; set; }

        [StringLength(20,MinimumLength =3)]
        public string Title { get; set; }

        [Range(1,4)]
        public int Credits { get; set; }

        [StringLength(20, ErrorMessage = "Location must be less than 20 charactes."), Display(Name = "Room Location")]
        public string RoomNumber { get; set; }
        
        public int DepartmentId { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        // Can have multiple instructors for a class. Also TAs and GAs
        public virtual ICollection<Instructor> Instructors { get; set; }
    }
}